(() => {
'use strict';
const $=id=>document.getElementById(id); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v)); const fmt=(n,d=2)=>Number(n).toFixed(d);
const st={playing:false,phase:0,last:0,raf:0,logs:[]};
document.addEventListener('DOMContentLoaded',()=>{initControls();initLocalExport();initPngButtons();});
function initControls(){if(document.querySelector('[data-viz-mode]')?.dataset.vizMode!=='soundDiffraction')return; ['vizSlit','vizFreq','vizTemp','vizAmp','vizTimeSpeed'].forEach(id=>{const el=$(id); if(!el)return; el.addEventListener('input',draw); el.addEventListener('change',draw);}); $('vizPlayBtn')?.addEventListener('click',play); $('vizPauseBtn')?.addEventListener('click',pause); $('vizResetBtn')?.addEventListener('click',reset); draw();}
function play(){if(st.playing)return; st.playing=true; st.last=performance.now(); cancelAnimationFrame(st.raf); st.raf=requestAnimationFrame(loop);} function pause(){st.playing=false; cancelAnimationFrame(st.raf); draw();} function reset(){st.playing=false; st.phase=0; st.last=0; cancelAnimationFrame(st.raf); draw();}
function loop(now){if(!st.playing)return; const p=params(); const dt=st.last?(now-st.last)/1000:0; st.last=now; st.phase+=dt*72*p.timeSpeed; draw(); st.raf=requestAnimationFrame(loop);}
function n(id,fb){const el=$(id), v=el?Number(el.value):NaN; return Number.isFinite(v)?v:fb;}
function params(){const f=n('vizFreq',600), temp=n('vizTemp',20), v=331+0.6*temp, lambda=v/f, a=n('vizSlit',0.6), amp=n('vizAmp',0.75), timeSpeed=n('vizTimeSpeed',1), ratio=a/lambda; const hasFirstMinimum=ratio>1; const theta1Rad=hasFirstMinimum?Math.asin(clamp(lambda/a,0,1)):Math.PI/2; const theta1Deg=theta1Rad*180/Math.PI; let strength='เด่นมาก'; if(ratio>3)strength='น้อย'; else if(ratio>1.3)strength='ปานกลาง'; else if(ratio>0.7)strength='เด่น'; return{f,temp,v,lambda,a,amp,timeSpeed,ratio,hasFirstMinimum,theta1Rad,theta1Deg,angleText:hasFirstMinimum?`${Math.round(theta1Deg)}°`:'แผ่กว้างมาก',angleNote:hasFirstMinimum?'first_sound_minimum_valid':'no_first_sound_minimum_within_90_deg',strength};}
function labels(p){txt('vizSlitLabel',`${fmt(p.a,2)} m`); txt('vizFreqLabel',`${Math.round(p.f)} Hz`); txt('vizTempLabel',`${Math.round(p.temp)} °C`); txt('vizAmpLabel',fmt(p.amp,2)); txt('vizTimeLabel',`${fmt(p.timeSpeed,1)}×`); txt('vizSpeedLabel',`${fmt(p.v,1)} m/s`); txt('vizLambdaLabel',`${fmt(p.lambda,2)} m`); txt('vizRatioLabel',fmt(p.ratio,2)); txt('vizAngleLabel',p.angleText); txt('vizStrengthLabel',p.strength);} function txt(id,t){const el=$(id); if(el)el.textContent=t;}
function prep(c){const r=c.getBoundingClientRect(), cssW=r.width||c.width||1200, cssH=Math.max(300,cssW*460/1200), dpr=Math.max(1,Math.min(2.5,devicePixelRatio||1)); c.style.height=`${cssH}px`; if(c.width!==Math.round(cssW*dpr)||c.height!==Math.round(cssH*dpr)){c.width=Math.round(cssW*dpr); c.height=Math.round(cssH*dpr);} const ctx=c.getContext('2d'); ctx.setTransform(dpr,0,0,dpr,0,0); return{ctx,w:cssW,h:cssH};}
function draw(){if(document.querySelector('[data-viz-mode]')?.dataset.vizMode!=='soundDiffraction')return; const c=$('visualizerCanvas'); if(!c)return; const {ctx,w,h}=prep(c), p=params(); labels(p); ctx.clearRect(0,0,w,h); bg(ctx,w,h); const wallX=w*.42, cy=h*.53, top=h*.13, bottom=h*.88, gapPx=clamp(p.a*h*.20,16,h*.55), spacing=clamp(p.lambda*105,24,92), phase=((st.phase%spacing)+spacing)%spacing, spread=p.hasFirstMinimum?p.theta1Rad:Math.PI/2; speaker(ctx,w*.10,cy,p.amp); incoming(ctx,wallX,top,bottom,spacing,phase,p.amp); wall(ctx,wallX,top,bottom,cy,gapPx); shadow(ctx,wallX,w,top,bottom,cy,gapPx); waves(ctx,wallX,cy,spacing,phase,p,w,h,spread); guides(ctx,wallX,cy,gapPx,spread,w,h,p); screen(ctx,w*.92,top,bottom,wallX,cy,p); badge(ctx,w,h,p);}
function bg(ctx,w,h){const g=ctx.createLinearGradient(0,0,w,h); g.addColorStop(0,'#071421'); g.addColorStop(.45,'#08111f'); g.addColorStop(1,'#050913'); ctx.fillStyle=g; ctx.fillRect(0,0,w,h); ctx.save(); ctx.strokeStyle='rgba(148,163,184,.10)'; for(let x=0;x<=w;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();} for(let y=0;y<=h;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();} ctx.restore(); const rg=ctx.createRadialGradient(w*.48,h*.52,0,w*.48,h*.52,Math.max(w,h)*.55); rg.addColorStop(0,'rgba(56,189,248,.12)'); rg.addColorStop(1,'rgba(56,189,248,0)'); ctx.fillStyle=rg; ctx.fillRect(0,0,w,h);}
function speaker(ctx,x,y,amp){ctx.save();ctx.translate(x,y);ctx.fillStyle='#1e293b';rr(ctx,-44,-30,36,60,10,true,false);ctx.fillStyle='#38bdf8';ctx.beginPath();ctx.moveTo(-8,-20);ctx.lineTo(25,-38);ctx.lineTo(25,38);ctx.lineTo(-8,20);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(224,242,254,.85)';ctx.lineWidth=2;for(let i=1;i<=3;i++){ctx.globalAlpha=.28+amp*.25;ctx.beginPath();ctx.arc(28,0,16+i*16,-.55,.55);ctx.stroke();}ctx.globalAlpha=1;ctx.fillStyle='#dbeafe';ctx.font='700 13px system-ui,sans-serif';ctx.fillText('แหล่งกำเนิดเสียง',-55,58);ctx.restore();}
function incoming(ctx,wallX,top,bottom,spacing,phase,amp){ctx.save();ctx.strokeStyle=`rgba(56,189,248,${.34+amp*.38})`;ctx.lineWidth=2.2;for(let x=wallX-phase;x>32;x-=spacing){ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke();}arrow(ctx,wallX*.25,top+18,wallX*.62,top+18,'rgba(248,250,252,.72)');ctx.fillStyle='rgba(226,232,240,.84)';ctx.font='700 13px system-ui,sans-serif';ctx.fillText('คลื่นเสียงตกกระทบกำแพงช่องเปิด',wallX*.25,top+8);ctx.restore();}
function wall(ctx,wallX,top,bottom,cy,gap){seg(ctx,wallX,top,cy-gap/2,28);seg(ctx,wallX,cy+gap/2,bottom,28);ctx.save();ctx.fillStyle='#dbeafe';ctx.font='800 13px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText('กำแพงช่องเปิดเดี่ยว',wallX,top-16);ctx.strokeStyle='#facc15';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(wallX+22,cy-gap/2);ctx.lineTo(wallX+22,cy+gap/2);ctx.stroke();ctx.fillStyle='#fde68a';ctx.font='800 12px system-ui,sans-serif';ctx.textAlign='left';ctx.fillText('a',wallX+30,cy+4);ctx.restore();}
function seg(ctx,wallX,y1,y2,ww){const h=y2-y1;if(h<=0)return;const g=ctx.createLinearGradient(wallX-ww/2,0,wallX+ww/2,0);g.addColorStop(0,'#1e293b');g.addColorStop(.5,'#475569');g.addColorStop(1,'#1e293b');ctx.fillStyle=g;rr(ctx,wallX-ww/2,y1,ww,h,7,true,true);ctx.strokeStyle='rgba(226,232,240,.14)';ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.08)';for(let y=y1+14;y<y2;y+=18){ctx.beginPath();ctx.moveTo(wallX-ww/2+4,y);ctx.lineTo(wallX+ww/2-4,y+6);ctx.stroke();}}
function shadow(ctx,wallX,w,top,bottom,cy,gap){ctx.save();ctx.fillStyle='rgba(15,23,42,.30)';ctx.beginPath();ctx.rect(wallX+16,top,w-wallX-16,Math.max(0,cy-gap/2-top));ctx.rect(wallX+16,cy+gap/2,w-wallX-16,Math.max(0,bottom-cy-gap/2));ctx.fill();ctx.fillStyle='rgba(203,213,225,.62)';ctx.font='700 12px system-ui,sans-serif';ctx.fillText('บริเวณเงาเสียง',wallX+42,top+26);ctx.restore();}
function waves(ctx,wallX,cy,spacing,phase,p,w,h,spread){ctx.save();ctx.lineWidth=2.15;const maxR=Math.hypot(w-wallX,h), base=.22+p.amp*.28;for(let r=phase+spacing*.45;r<maxR;r+=spacing){const fade=clamp(1-r/(maxR*1.05),.12,1);ctx.strokeStyle=`rgba(56,189,248,${base*fade})`;ctx.beginPath();ctx.arc(wallX,cy,r,-spread,spread);ctx.stroke();} if(p.a>p.lambda*1.35){const count=clamp(Math.round(p.a/p.lambda)+2,3,8), ap=clamp(p.a*h*.20,16,h*.55);for(let i=0;i<count;i++){const hy=cy-ap/2+ap*(i+.5)/count;ctx.strokeStyle='rgba(125,211,252,.13)';for(let r=phase*.7+spacing;r<maxR*.65;r+=spacing*1.4){ctx.beginPath();ctx.arc(wallX,hy,r,-spread,spread);ctx.stroke();}}}ctx.restore();}
function guides(ctx,wallX,cy,gap,spread,w,h,p){const endX=w*.90,len=endX-wallX,y1=cy-Math.tan(spread)*len,y2=cy+Math.tan(spread)*len;ctx.save();ctx.setLineDash([8,8]);ctx.strokeStyle='rgba(251,113,133,.78)';ctx.lineWidth=2;line(ctx,wallX,cy,endX,clamp(y1,8,h-8));line(ctx,wallX,cy,endX,clamp(y2,8,h-8));ctx.setLineDash([]);arrow(ctx,wallX+14,cy,endX,cy,'rgba(248,250,252,.36)');ctx.fillStyle='rgba(251,113,133,.92)';ctx.font='800 13px system-ui,sans-serif';ctx.fillText(p.hasFirstMinimum?`θ₁ ≈ ${Math.round(p.theta1Deg)}°`:'แผ่กว้างมาก',wallX+54,cy-18);ctx.strokeStyle='rgba(250,204,21,.55)';ctx.setLineDash([5,7]);line(ctx,wallX+18,cy-gap/2,endX,cy-gap/2);line(ctx,wallX+18,cy+gap/2,endX,cy+gap/2);ctx.setLineDash([]);ctx.restore();}
function screen(ctx,x,top,bottom,wallX,mid,p){ctx.save();ctx.strokeStyle='rgba(226,232,240,.48)';ctx.lineWidth=2;line(ctx,x,top,x,bottom);ctx.fillStyle='rgba(226,232,240,.86)';ctx.font='700 12px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText('ฉากรับ/แนวผู้ฟัง',x,bottom+20);ctx.textAlign='left';ctx.fillStyle='rgba(216,180,254,.92)';ctx.fillText('I/I₀ ความเข้มเสียงสัมพัทธ์',x+12,top-10);const dist=x-wallX;let maxY=mid,maxI=0;for(let y=top;y<=bottom;y+=3){const theta=Math.atan2(y-mid,dist),I=single(theta,p.a,p.lambda);if(I>maxI){maxI=I;maxY=y;}const alpha=clamp(I*p.amp,.03,.95),wid=8+I*34;ctx.fillStyle=`rgba(167,139,250,${alpha})`;rr(ctx,x+8,y-1.3,wid,2.6,2,true,false);}ctx.strokeStyle='rgba(255,255,255,.40)';ctx.setLineDash([4,6]);line(ctx,x-8,mid,x+48,mid);ctx.setLineDash([]);ctx.fillStyle='rgba(226,232,240,.76)';ctx.font='700 11px system-ui,sans-serif';ctx.textAlign='left';ctx.fillText('เสียงเข้มสุด',x+50,mid+4);ctx.fillText('บริเวณเสียงเบากว่า',x+42,top+30);ctx.restore();}
function single(theta,a,lambda){const b=Math.PI*a*Math.sin(theta)/lambda;if(Math.abs(b)<1e-5)return 1;const v=Math.sin(b)/b;return v*v;}
function badge(ctx,w,h,p){ctx.save();const third=p.hasFirstMinimum?`θ₁ จาก a sinθ₁ = λ ≈ ${Math.round(p.theta1Deg)}°`:'a ≤ λ: ไม่มีตำแหน่งเสียงเบามากแรกในช่วง 0–90°';const lines=[`λ = v/f = ${fmt(p.lambda,2)} m`,`a/λ = ${fmt(p.ratio,2)}  →  การเลี้ยวเบน${p.strength}`,third];const x=18,y=h-88,bw=Math.min(w-36,560),bh=74;ctx.fillStyle='rgba(2,6,23,.62)';ctx.strokeStyle='rgba(148,163,184,.24)';rr(ctx,x,y,bw,bh,18,true,true);ctx.fillStyle='#e0f2fe';ctx.font='800 14px system-ui,sans-serif';ctx.fillText(lines[0],x+14,y+24);ctx.fillStyle=p.ratio<=1.3?'#86efac':p.ratio<=3?'#fde68a':'#fecaca';ctx.fillText(lines[1],x+14,y+45);ctx.fillStyle='rgba(226,232,240,.82)';ctx.font='700 12px system-ui,sans-serif';ctx.fillText(lines[2],x+14,y+64);ctx.restore();}
function line(ctx,x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function arrow(ctx,x1,y1,x2,y2,color='rgba(248,250,252,.8)'){const a=Math.atan2(y2-y1,x2-x1);ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;line(ctx,x1,y1,x2,y2);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-10*Math.cos(a-Math.PI/6),y2-10*Math.sin(a-Math.PI/6));ctx.lineTo(x2-10*Math.cos(a+Math.PI/6),y2-10*Math.sin(a+Math.PI/6));ctx.closePath();ctx.fill();ctx.restore();}
function rr(ctx,x,y,w,h,r,fill=true,stroke=false){const q=Math.min(r,Math.abs(w)/2,Math.abs(h)/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath();if(fill)ctx.fill();if(stroke)ctx.stroke();}
function currentRow(){const now=new Date(),p=params();return{timestamp:now.toISOString(),topic:'Sound Diffraction',model:'single_opening_diffraction',frequency_Hz:Math.round(p.f),temperature_C:Math.round(p.temp),speed_m_s:Number(fmt(p.v,2)),wavelength_m:Number(fmt(p.lambda,4)),aperture_a_m:Number(fmt(p.a,3)),aperture_over_lambda:Number(fmt(p.ratio,3)),theta1_deg:p.hasFirstMinimum?Number(fmt(p.theta1Deg,1)):'',theta1_note:p.angleNote,diffraction_strength:p.strength,amplitude_display_A:Number(fmt(p.amp,2)),time_speed_x:Number(fmt(p.timeSpeed,2)),physics_note:p.hasFirstMinimum?'a sin(theta1) = lambda (first minimum of relative sound intensity, approximate)':'a <= lambda; no first sound-intensity minimum within 0-90 degrees; broad spreading'};}
function initLocalExport(){const card=document.querySelector('.localExportCard'); if(!card)return; card.querySelector('.localCaptureBtn')?.addEventListener('click',()=>{st.logs.push(currentRow());renderLog();}); card.querySelector('.localDownloadBtn')?.addEventListener('click',downloadCsv); card.querySelector('.localClearBtn')?.addEventListener('click',()=>{st.logs=[];renderLog();}); renderLog();}
function renderLog(){const head=document.querySelector('.localHead'),body=document.querySelector('.localBody'); if(!head||!body)return; const sample=st.logs[0]||currentRow(), keys=Object.keys(sample); head.innerHTML=keys.map(k=>`<th>${esc(k)}</th>`).join(''); body.innerHTML=st.logs.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k]??'')}</td>`).join('')}</tr>`).join('');}
function downloadCsv(){if(!st.logs.length)st.logs.push(currentRow()); const keys=Object.keys(st.logs[0]); const rows=[keys.join(',')].concat(st.logs.map(r=>keys.map(k=>csv(r[k])).join(','))); const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8;'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`soundDiffraction_${new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')}.csv`; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},500); renderLog();}
function csv(v){const s=String(v??''); return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;} function esc(v){return String(v??'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));}
function initPngButtons(){const set=new Set(); ['vizScreenBtn','vizExportBtn'].forEach(id=>{const el=$(id); if(el&&!set.has(el)){set.add(el);el.addEventListener('click',savePng);}}); $$('.localPngBtn').forEach(el=>{if(!set.has(el)){set.add(el);el.addEventListener('click',savePng);}});}
function savePng(){const c=$('visualizerCanvas'); if(!c)return; draw(); try{c.toBlob(blob=>{if(!blob){fallback(c);return;} const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='soundDiffraction.png'; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},500);},'image/png');}catch(e){fallback(c);}}
function fallback(c){const b=document.createElement('div');b.className='pngModalBackdrop';const m=document.createElement('div');m.className='pngModal';m.innerHTML=`<p>ถ้าดาวน์โหลดไม่ได้ ให้แตะค้างหรือคลิกขวาที่ภาพเพื่อบันทึก</p><img alt="ภาพจำลอง" src="${c.toDataURL('image/png')}"><button class="secondary">ปิด</button>`;m.querySelector('button').addEventListener('click',()=>b.remove());b.addEventListener('click',e=>{if(e.target===b)b.remove();});b.appendChild(m);document.body.appendChild(b);}
})();